// reactclient/src/components/Calculator.jsx
import React from "react";
// API
import api from "../api";
// Context
import { editStack } from "../context/actions/stack";
// Components
import Stack from "./calculator/Stack";
import Operands from "./calculator/Operands";

export default function Calculator({ stack, operands, dispatch }) {
  const [input, setInput] = React.useState(null);

  const handleOnChange = React.useCallback((e) => {
    const strValue = e.target.value;

    if (strValue === "") {
      setInput(null);
    } else {
      const value = parseFloat(strValue);

      if (isNaN(value)) return;

      setInput(value);
    }
  }, []);

  const handleOnClick = React.useCallback(async () => {
    console.log(typeof input);

    if (!input) return;

    const payload = await api.pushValue(stack.id, input);
    dispatch(editStack(payload));

    setInput("");
  }, [input, stack, dispatch]);

  return (
    <div style={{ width: "30vw", height: "70vh" }} className="card">
      <div className="card-header h3 text-center text-uppercase bg-dark text-white">
        RPN Calculator
      </div>
      <div className="card-body bg-info d-flex  flex-column h-100">
        <div className="d-flex">
          <div className="flex-grow-1">
            <input
              type="text"
              className="input-group"
              onChange={(e) => handleOnChange(e)}
              value={input !== null ? input : ""}
            />
          </div>
          <div className="ml-2">
            <button
              type="button"
              style={{
                width: "6rem",
                fontWeight: 600,
              }}
              className="btn btn-sm btn-success d-block mx-1"
              onClick={() => handleOnClick()}
            >
              Enter
            </button>
          </div>
        </div>
        <div className="flex-grow-1 d-flex">
          <Stack stack={stack} />
          <Operands stack={stack} operands={operands} dispatch={dispatch} />
        </div>
      </div>
    </div>
  );
}

// angularclient/src/app/components/calculator/calculator.component.ts
import { Component, OnInit, Input, Output, EventEmitter } from '@angular/core';

// Services
import { StackService } from '../../services/stack.service';
// Models
import { Stack } from '../../models/stack';

@Component({
  selector: 'app-calculator',
  templateUrl: './calculator.component.html',
  styleUrls: ['./calculator.component.css'],
})
export class CalculatorComponent implements OnInit {
  title: string = 'RPN Calculator';

  operands: string[];
  inputValue: string = '';

  @Input()
  selectedStack: Stack;

  @Output()
  applyOperand: EventEmitter<{
    operand: string;
    stackId: number;
  }> = new EventEmitter<{ operand: string; stackId: number }>();

  @Output()
  pushValue: EventEmitter<{
    stackId: number;
    value: number;
  }> = new EventEmitter<{
    stackId: number;
    value: number;
  }>();

  constructor(private stackService: StackService) {}

  ngOnInit(): void {
    this.stackService.getOperands().subscribe((operands) => {
      this.operands = operands;
    });
  }

  onChange(e): void {
    if (isNaN(parseFloat(e.target.value))) return;

    this.inputValue = e.target.value;
  }

  onApply(operand): void {
    this.applyOperand.emit({ operand, stackId: this.selectedStack.id });
  }

  onPush(): void {
    if (isNaN(parseFloat(this.inputValue)) || !this.selectedStack) return;

    this.pushValue.emit({
      stackId: this.selectedStack.id,
      value: parseFloat(this.inputValue),
    });

    this.inputValue = '';
  }
}

<div id="calculator" class="card">
  <div class="card-header h3 text-center text-uppercase bg-dark text-white">
    {{ title }}
  </div>
  <div class="card-body bg-info d-flex flex-column h-100">
    <div class="d-flex">
      <div class="flex-grow-1">
        <input
          type="text"
          class="input-group"
          [value]="inputValue"
          (change)="onChange($event)"
        />
      </div>
      <div class="ml-2">
        <button
          id="enter-btn"
          type="button"
          class="btn btn-sm btn-success d-block mx-1"
          (click)="onPush()"
        >
          Enter
        </button>
      </div>
    </div>
    <div class="flex-grow-1 d-flex">
      <div id="stack" class="flex-grow-1 mt-2 bg-dark">
        <ng-container *ngIf="selectedStack">
          <p
            *ngFor="let data of selectedStack.values; let i = index"
            class="ml-2 text-white"
          >
            {{ i }} -> {{ data.value }}
          </p>
        </ng-container>
      </div>
      <app-operands
        selectedStack="selectedStack"
        [operands]="operands"
        (applyOperand)="onApply($event)"
      ></app-operands>
    </div>
  </div>
</div>
