// angularclient/src/app/components/stack/stack.component.ts
import { Component, OnInit, Input, Output, EventEmitter } from '@angular/core';

// Models
import { Stack } from '../../models/stack';

@Component({
  selector: 'app-stack',
  templateUrl: './stack.component.html',
  styleUrls: ['./stack.component.css'],
})
export class StackComponent {
  @Input()
  stack: Stack;

  @Output()
  selectStack: EventEmitter<Stack> = new EventEmitter<Stack>();

  @Output()
  deleteStack: EventEmitter<Stack> = new EventEmitter<Stack>();

  constructor() {}

  onSelect(stack) {
    this.selectStack.emit(stack);
  }

  onDelete(stack) {
    this.deleteStack.emit(stack.id);
  }
}

<div class="d-flex justify-content-between align-items-center mt-2">
  <div class="flex-grow-1 btn btn-sm btn-info" (click)="onSelect(stack)">
    {{ stack.id }}
  </div>
  <button
    type="button"
    class="ml-2 btn btn-sm btn-danger"
    (click)="onDelete(stack)"
  >
    Delete
  </button>
</div>

// reactclient/src/components/displayer/Stack.jsx
import React from "react";
// API
import api from "../../api";
// Context
import { selectStack, deleteStack } from "../../context/actions/stack";

export default function Stack({ stack, dispatch }) {
  const handleSelect = React.useCallback(() => {
    dispatch(selectStack(stack.id));
  }, [dispatch, stack]);

  const handleDelete = React.useCallback(async () => {
    const payload = await api.deleteStack(stack.id);

    dispatch(deleteStack(stack.id));
  }, [dispatch, stack]);

  return (
    <div className="d-flex justify-content-between align-items-center mt-2">
      <div
        style={{
          fontWeight: 600,
        }}
        className="flex-grow-1 btn btn-sm btn-info"
        onClick={() => handleSelect()}
      >
        {stack.id}
      </div>
      <button
        style={{
          fontWeight: 600,
        }}
        type="button"
        className="ml-2 btn btn-sm btn-danger"
        onClick={() => handleDelete()}
      >
        Delete
      </button>
    </div>
  );
}
