// reactclient/src/components/StackDisplayer.jsx
import React from "react";
// Components
import StackList from "./displayer/StackList";

export default function StackDisplayer({ stacks, dispatch }) {
  return (
    <div style={{ width: "20vw", height: "70vh" }} className="card ml-5">
      <div className="card-header h3 text-center text-uppercase bg-info text-white">
        Stacks
      </div>
      <div className="card-body bg-dark d-flex  flex-column h-100">
        <StackList stacks={stacks} dispatch={dispatch} />
      </div>
    </div>
  );
}

// angularclient/src/app/components/stackdisplayer/stackdisplayer.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';

// Models
import { Stack } from '../../models/stack';

@Component({
  selector: 'app-stackdisplayer',
  templateUrl: './stackdisplayer.component.html',
  styleUrls: ['./stackdisplayer.component.css'],
})
export class StackDisplayerComponent {
  title: string = 'Stacks';

  @Input()
  stacks: Stack[];

  @Output()
  createStack: EventEmitter<Stack> = new EventEmitter<Stack>();

  @Output()
  selectStack: EventEmitter<Stack> = new EventEmitter<Stack>();

  @Output()
  deleteStack: EventEmitter<number> = new EventEmitter<number>();

  constructor() {}

  onCreate(): void {
    this.createStack.emit();
  }

  onSelect(stack: Stack): void {
    this.selectStack.emit(stack);
  }

  onDelete(stackId: number): void {
    this.deleteStack.emit(stackId);
  }
}

<div id="stack-displayer" class="card ml-5">
  <div class="card-header h3 text-center text-uppercase bg-info text-white">
    {{ title }}
  </div>
  <div id="stack-list" class="card-body bg-dark d-flex flex-column h-100">
    <button
      type="button"
      class="btn btn-sm btn-success w-100 mb-2"
      (click)="onCreate()"
    >
      +
    </button>
    <app-stack
      *ngFor="let stack of stacks"
      [stack]="stack"
      (deleteStack)="onDelete($event)"
      (selectStack)="onSelect($event)"
    ></app-stack>
  </div>
</div>
